// <auto-generated />
using System;
using ContactManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactManager.Infrastructure.Migrations
{
    [DbContext(typeof(ContactManagerDbContext))]
    [Migration("20250905171448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ContactManager.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Gender")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumberBusiness")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumberMobile")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumberPrivate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Place")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salutation")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ZipCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("People", (string)null);

                    b.HasDiscriminator().HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ContactManager.Domain.Entities.Customer", b =>
                {
                    b.HasBaseType("ContactManager.Domain.Entities.Person");

                    b.Property<string>("CompanyContact")
                        .HasColumnType("TEXT")
                        .HasColumnName("CompanyContact");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT")
                        .HasColumnName("CompanyName");

                    b.Property<string>("CustomerType")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("CustomerType");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("ContactManager.Domain.Entities.Employee", b =>
                {
                    b.HasBaseType("ContactManager.Domain.Entities.Person");

                    b.Property<int?>("CadreLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CadreLevel");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT")
                        .HasColumnName("Department");

                    b.Property<Guid>("EmployeeNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("EmployeeNumber");

                    b.Property<int?>("Employment")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Employment");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("EndDate");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT")
                        .HasColumnName("Role");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartDate");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("ContactManager.Domain.Entities.Trainee", b =>
                {
                    b.HasBaseType("ContactManager.Domain.Entities.Employee");

                    b.Property<int?>("ActualTraineeYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ActualTraineeYear");

                    b.Property<int?>("TraineeYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TraineeYears");

                    b.HasDiscriminator().HasValue("Trainee");
                });
#pragma warning restore 612, 618
        }
    }
}
